version: "3"

networks:
  php-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  mysql-backend:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  mysqldb:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      mysql-backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./config.env
  php-www:
    build: ./www
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    networks:
      mysql-backend:
        ipv4_address: 172.10.2.2
      php-frontend:
        ipv4_address: 172.10.1.2
    depends_on:
      - mysqldb
    env_file:
      - ./config.env